<template>
  <div id="container">
    <div class="row">
      <div class="col"></div>
      <div class="col" style="margin-top: 100px;">
        <ul class="loginCenter">
          <li>이메일을 입력해 주세요</li>
          <li><input type="text" class="mb-2 " id="email" @keyup.enter="tryLogin" placeholder="email" v-model="email">
          </li>
          <li>비밀번호를 입력해 주세요</li>
          <li><input type="password" class="center" @keyup.enter="tryLogin" placeholder="password" id="pwd"
              v-model="pwd"></li>
          <li><input type="button" class="mt-3" @click="tryLogin" value="로그인"></li>
          <li><a href="/findAccountPage?scope=email" class="mr20">이메일 찾기</a><br><a
              href="/findAccountPage?scope=pwd">비밀번호 찾기</a></li>
          <li><button @click="localLogin">로컬 로그인 하기</button></li>
        </ul>
      </div>
      <div class="col"></div>
    </div>
  </div>
  {{ assertions }}
  {{ errs }}
  {{creds}}
  test
</template>
<style scoped>
li {
  list-style: none;
}
</style>
<script>
export default {
  name: 'loginPage',
  data() {
    return {
      email: null,
      pwd: null,
      assertions: null,
      errs: null,
      creds:null
    }
  },
  methods: {
    tryLogin() {
      this.$store.dispatch('basicStore/requestLogin', { email: this.email, pwd: this.pwd, nextUrl: this.$route.query.nextUrl });
    },
    localLogin() {
     // credentialId is generated by the authenticator and is an opaque random byte array
            var credentialId = new Uint8Array([183, 148, 245,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]);
            var options = {
                // The challenge is produced by the server; see the Security Considerations
                challenge: new Uint8Array([4, 101, 15 ,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]),
                timeout: 120000,  // 2 minutes
                allowCredentials: [{ type: "public-key", id: credentialId }]
            };
            navigator.credentials.get({ "publicKey": options })
                .then(function (assertion) {
                    console.log(assertion);
                    // Send assertion to server for verification
                }).catch(function (err) {
                    console.log(err);
                    // No acceptable credential or user refused consent. Handle appropriately.
                });
    }
  }
}
</script>

