<template>
    <div style="margin-top: 100px;">
        <button @click="upsertLocalLogin">생체 인증 수단 등록/수정</button>
        <button @click="temp">생체 인증 수단</button>
    </div>
    {{ creds }}
</template>

<script>
// const createCredentialDefaultArgs = {
//   publicKey: {
//     // Relying Party (a.k.a. - Service):
//     rp: {
//       name: "Acme"
//     },

//     // User:
//     user: {
//       id: new Uint8Array(16),
//       name: '',
//       displayName: ""
//     },

//     pubKeyCredParams: [{
//       type: "public-key",
//       alg: -7
//     }],

//     attestation: "direct",

//     timeout: 60000,

//     challenge: new Uint8Array([ // must be a cryptographically random number sent from a server
//       0, 1, 2,3, 4, 5, 6, 7, 0xB9, 0x4E, 0x2E, 0x17, 0x1A, 0x98, 0x6A, 0x73,
//       0x71, 0x9D, 0x43, 0x48, 0xD5, 0xA7, 0x6A, 0x15, 0x7E, 0x38, 0x94, 0x52, 0x77, 0x97, 0x0F, 0xEF
//     ]).buffer
//   }
// };
// // sample arguments for login
// const getCredentialDefaultArgs = {
//   publicKey: {
//     timeout: 60000,
//     // allowCredentials: [newCredential] // see below
//     challenge: new Uint8Array([ // must be a cryptographically random number sent from a server
//       0x79, 0x50, 0x68, 0x71, 0xDA, 0xEE, 0xEE, 0xB9, 0x94, 0xC3, 0xC2, 0x15, 0x67, 0x65, 0x26, 0x22,
//       0xE3, 0xF3, 0xAB, 0x3B, 0x78, 0x2E, 0xD5, 0x6F, 0x81, 0x26, 0xE2, 0xA6, 0x01, 0x7D, 0x74, 0x50
//     ]).buffer
//   },
// };
export default {
    data() {
        return {
            creds: null
        }
    },
    methods: {
        async upsertLocalLogin() {
            var publicKey = {
                // The challenge is produced by the server; see the Security Considerations
                challenge: new Uint8Array([21, 31, 105 /* 29 more random bytes generated by the server */]),

                // Relying Party:
                rp: {
                    name: "ACME Corporation"
                },

                // User:
                user: {
                    id: Uint8Array.from(window.atob("MIIBkzCCATigAwIBAjCCAZMwggE4oAMCAQIwggGTMII="), c => c.charCodeAt(0)),
                    name: "alex.mueller@example.com",
                    displayName: "Alex Müller",
                },

                // This Relying Party will accept either an ES256 or RS256 credential, but
                // prefers an ES256 credential.
                pubKeyCredParams: [
                    {
                        type: "public-key",
                        alg: -7 // "ES256" as registered in the IANA COSE Algorithms registry
                    },
                    {
                        type: "public-key",
                        alg: -257 // Value registered by this specification for "RS256"
                    }
                ],

                authenticatorSelection: {
                    // Try to use UV if possible. This is also the default.
                    userVerification: "preferred"
                },

                timeout: 360000,  // 6 minutes
                excludeCredentials: [
                    // Don’t re-register any authenticator that has one of these credentials
                    { "id": Uint8Array.from(window.atob("ufJWp8YGlibm1Kd9XQBWN1WAw2jy5In2Xhon9HAqcXE="), c => c.charCodeAt(0)), "type": "public-key" },
                    { "id": Uint8Array.from(window.atob("E/e1dhZc++mIsz4f9hb6NifAzJpF1V4mEtRlIPBiWdY="), c => c.charCodeAt(0)), "type": "public-key" }
                ],

                // Make excludeCredentials check backwards compatible with credentials registered with U2F
                extensions: { "appidExclude": "https:/localhost:3030/" }
            };
            // Note: The following call will cause the authenticator to display UI.
            navigator.credentials.create({ publicKey })
                .then(function (newCredentialInfo) {
                    console.log(newCredentialInfo);
                    // Send new credential info to server for verification and registration.
                }).catch(function (err) {
                    console.log(err);
                    // No acceptable authenticator or user refused consent. Handle appropriately.
                });
        },
        temp() {
            // credentialId is generated by the authenticator and is an opaque random byte array
            var credentialId = new Uint8Array([183, 148, 245,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]);
            var options = {
                // The challenge is produced by the server; see the Security Considerations
                challenge: new Uint8Array([4, 101, 15 ,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]),
                timeout: 120000,  // 2 minutes
                allowCredentials: [{ type: "public-key", id: credentialId }]
            };

            navigator.credentials.get({ "publicKey": options })
                .then(function (assertion) {
                    console.log(assertion);
                    // Send assertion to server for verification
                }).catch(function (err) {
                    console.log(err);
                    // No acceptable credential or user refused consent. Handle appropriately.
                });
        }
    }
}
</script>

<style>
</style>